# Generated by Django 4.1.7 on 2023-04-30 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_post_review_like_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='author',
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
