# Generated by Django 4.1.7 on 2023-04-30 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_post_comments_post_likes_post_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='reviews',
        ),
    ]
