# Generated by Django 4.1.7 on 2023-05-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_comment_post_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='reviews', to='website.review'),
        ),
    ]
