version: '3.8'

services:

  web:
    build: ./project
    command: python /app/project/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db

  chat:
    build: ./globalchat
    ports:
      - "8001:8001"
    volumes:
      - ./globalchat:/app

  db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL2505
      MYSQL_DATABASE: MealMateDB
      MYSQL_USER: MichaelBAW
      MYSQL_PASSWORD: MBAW2505
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  

volumes:
  mysql_data:
