# Generated by Django 4.1.7 on 2023-05-07 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_profilepicture_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilePicture',
        ),
    ]
