# Generated by Django 4.1.7 on 2023-05-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_delete_profilepicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_pics')),
                ('name', models.TextField()),
            ],
        ),
    ]
