# Generated by Django 4.1.7 on 2023-05-03 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_post_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
