# Generated by Django 4.1.7 on 2023-05-03 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
