# Generated by Django 4.1.7 on 2023-05-03 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remove_review_post_post_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
